/**
 * @file patternGenerator.js
 * @description Dynamic pattern/sequence challenge generator for Class Saathi Brain Training.
 *              Produces 6 types of number & shape patterns with plausible distractor options.
 *              All patterns are generated procedurally — no static question banks.
 */

// ─── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Random integer between min and max (inclusive).
 * @param {number} min
 * @param {number} max
 * @returns {number}
 */
const randInt = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;

/**
 * Pick a random element from an array.
 * @template T
 * @param {T[]} arr
 * @returns {T}
 */
const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];

/**
 * Shuffle an array (Fisher-Yates) and return a new copy.
 * @template T
 * @param {T[]} arr
 * @returns {T[]}
 */
const shuffle = (arr) => {
  const copy = [...arr];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
};

/**
 * Build 4 multiple-choice options: 1 correct + 3 plausible distractors.
 * Distractors are generated by applying small offsets to the correct answer.
 * @param {number} correct - The correct answer
 * @returns {{ id: string, text: string }[]}
 */
const buildOptions = (correct) => {
  const distractorSet = new Set();

  // Generate plausible distractors — off by 1, 2, or wrong operation results
  const offsets = [-2, -1, 1, 2, 3, -3];
  const shuffledOffsets = shuffle(offsets);

  for (const offset of shuffledOffsets) {
    const d = correct + offset;
    if (d !== correct && d >= 0) {
      distractorSet.add(d);
    }
    if (distractorSet.size >= 3) break;
  }

  // Fallback: if we don't have 3, add more
  let fallback = 4;
  while (distractorSet.size < 3) {
    distractorSet.add(correct + fallback);
    fallback++;
  }

  const distractors = Array.from(distractorSet).slice(0, 3);
  const ids = ['a', 'b', 'c', 'd'];

  // Combine and shuffle
  const allValues = shuffle([correct, ...distractors]);

  return allValues.map((val, i) => ({
    id: ids[i],
    text: String(val),
  }));
};

// ─── Pattern Generators (by type) ──────────────────────────────────────────────

/**
 * Arithmetic pattern: constant difference.
 * e.g. +3 → 2, 5, 8, 11, ?
 * @param {number} termCount - Number of visible terms (answer is the last)
 * @returns {{ sequence: (number|string)[], answer: number, rule: string, hintText: string }}
 */
const generateArithmetic = (termCount) => {
  const start = randInt(1, 20);
  const diff = randInt(2, 12);
  const terms = [];

  for (let i = 0; i < termCount; i++) {
    terms.push(start + diff * i);
  }

  const answer = terms[terms.length - 1];
  const sequence = [...terms.slice(0, -1), '?'];

  return {
    sequence,
    answer,
    rule: `Add ${diff}`,
    hintText: 'Look at the difference between consecutive numbers',
  };
};

/**
 * Geometric pattern: constant ratio.
 * e.g. ×2 → 3, 6, 12, 24, ?
 * @param {number} termCount
 * @returns {{ sequence: (number|string)[], answer: number, rule: string, hintText: string }}
 */
const generateGeometric = (termCount) => {
  const start = randInt(1, 5);
  const ratio = pick([2, 3, 4, 5]);
  const terms = [];

  let current = start;
  for (let i = 0; i < termCount; i++) {
    terms.push(current);
    current *= ratio;
  }

  const answer = terms[terms.length - 1];
  const sequence = [...terms.slice(0, -1), '?'];

  return {
    sequence,
    answer,
    rule: `Multiply by ${ratio}`,
    hintText: 'Try dividing each number by the previous one',
  };
};

/**
 * Alternating pattern: two interleaved arithmetic sub-sequences.
 * e.g. positions 0,2,4 follow +2 while positions 1,3,5 follow +3
 * → 1, 3, 3, 6, 5, 9, ?
 * @param {number} termCount
 * @returns {{ sequence: (number|string)[], answer: number, rule: string, hintText: string }}
 */
const generateAlternating = (termCount) => {
  const startA = randInt(1, 10);
  const startB = randInt(1, 10);
  const diffA = randInt(2, 5);
  const diffB = randInt(2, 5);

  const terms = [];
  for (let i = 0; i < termCount; i++) {
    if (i % 2 === 0) {
      terms.push(startA + diffA * Math.floor(i / 2));
    } else {
      terms.push(startB + diffB * Math.floor(i / 2));
    }
  }

  const answer = terms[terms.length - 1];
  const sequence = [...terms.slice(0, -1), '?'];

  return {
    sequence,
    answer,
    rule: `Two interleaved sequences: +${diffA} and +${diffB}`,
    hintText: 'Try looking at every other number separately',
  };
};

/**
 * Square or cube pattern: n², n³, or (n+k)².
 * @param {number} termCount
 * @returns {{ sequence: (number|string)[], answer: number, rule: string, hintText: string }}
 */
const generateSquareCube = (termCount) => {
  const isCube = Math.random() < 0.35;
  const offset = randInt(0, 3); // start from (1+offset)

  const terms = [];
  for (let i = 0; i < termCount; i++) {
    const n = i + 1 + offset;
    terms.push(isCube ? n * n * n : n * n);
  }

  const answer = terms[terms.length - 1];
  const sequence = [...terms.slice(0, -1), '?'];

  const label = isCube ? 'Cube' : 'Square';
  const startN = 1 + offset;

  return {
    sequence,
    answer,
    rule: `${label} numbers starting from ${startN}`,
    hintText: isCube
      ? 'Try finding the cube root of each number'
      : 'Try finding the square root of each number',
  };
};

/**
 * Fibonacci-like pattern: each term = sum of two previous terms.
 * @param {number} termCount
 * @returns {{ sequence: (number|string)[], answer: number, rule: string, hintText: string }}
 */
const generateFibonacci = (termCount) => {
  const a = randInt(1, 5);
  const b = randInt(1, 5);
  const terms = [a, b];

  for (let i = 2; i < termCount; i++) {
    terms.push(terms[i - 1] + terms[i - 2]);
  }

  const answer = terms[terms.length - 1];
  const sequence = [...terms.slice(0, -1), '?'];

  return {
    sequence,
    answer,
    rule: 'Each number is the sum of the two before it',
    hintText: 'Add consecutive pairs of numbers — what do you notice?',
  };
};

/**
 * Shape pattern: repeating cycle of emoji shapes.
 * The sequence shows shapes and the player must predict the next one.
 * Uses index-based answer for the option system.
 * @param {number} termCount
 * @returns {{ sequence: (string)[], answer: string, rule: string, hintText: string, isShape: boolean }}
 */
const generateShapePattern = (termCount) => {
  const allShapes = ['▲', '■', '●', '◆', '★', '⬟', '⬡'];
  const cycleLen = pick([2, 3, 4]);
  const cycle = shuffle(allShapes).slice(0, cycleLen);

  const terms = [];
  for (let i = 0; i < termCount; i++) {
    terms.push(cycle[i % cycleLen]);
  }

  const answer = terms[terms.length - 1];
  const sequence = [...terms.slice(0, -1), '?'];

  return {
    sequence,
    answer,
    rule: `Repeating pattern of ${cycleLen} shapes: ${cycle.join(' ')}`,
    hintText: `Look for a repeating group of ${cycleLen} shapes`,
    isShape: true,
  };
};

/**
 * Build multiple-choice options for shape patterns.
 * @param {string} correct - The correct shape
 * @returns {{ id: string, text: string }[]}
 */
const buildShapeOptions = (correct) => {
  const allShapes = ['▲', '■', '●', '◆', '★', '⬟', '⬡'];
  const distractors = shuffle(allShapes.filter((s) => s !== correct)).slice(0, 3);
  const ids = ['a', 'b', 'c', 'd'];
  const all = shuffle([correct, ...distractors]);
  return all.map((val, i) => ({ id: ids[i], text: val }));
};

// ─── Difficulty Mapping ────────────────────────────────────────────────────────

/**
 * Map difficulty to allowed pattern types and term counts.
 * @param {'easy' | 'medium' | 'hard'} difficulty
 * @returns {{ types: string[], termCount: number }}
 */
const getDifficultyConfig = (difficulty) => {
  switch (difficulty) {
    case 'easy':
      return { types: ['arithmetic'], termCount: 5 };
    case 'medium':
      return { types: ['geometric', 'alternating', 'shape'], termCount: pick([5, 6]) };
    case 'hard':
      return { types: ['squareCube', 'fibonacci', 'alternating', 'shape'], termCount: pick([6, 7]) };
    default:
      return { types: ['arithmetic'], termCount: 5 };
  }
};

// ─── Public API ────────────────────────────────────────────────────────────────

/**
 * Generate a pattern challenge at the specified difficulty.
 *
 * @param {'easy' | 'medium' | 'hard'} difficulty
 * @returns {{
 *   sequence: (number|string)[],
 *   answer: number | string,
 *   options: { id: string, text: string }[],
 *   rule: string,
 *   hintText: string,
 *   patternType: string
 * }}
 *
 * @example
 *   generatePatternChallenge('easy')
 *   // → {
 *   //   sequence: [2, 4, 6, 8, '?'],
 *   //   answer: 10,
 *   //   options: [{ id: 'a', text: '10' }, { id: 'b', text: '12' }, ...],
 *   //   rule: 'Add 2',
 *   //   hintText: 'Look at the difference between consecutive numbers',
 *   //   patternType: 'arithmetic'
 *   // }
 */
export const generatePatternChallenge = (difficulty = 'easy') => {
  const config = getDifficultyConfig(difficulty);
  const patternType = pick(config.types);

  let result;

  switch (patternType) {
    case 'arithmetic':
      result = generateArithmetic(config.termCount);
      break;
    case 'geometric':
      result = generateGeometric(config.termCount);
      break;
    case 'alternating':
      result = generateAlternating(config.termCount);
      break;
    case 'squareCube':
      result = generateSquareCube(config.termCount);
      break;
    case 'fibonacci':
      result = generateFibonacci(config.termCount);
      break;
    case 'shape':
      result = generateShapePattern(config.termCount);
      break;
    default:
      result = generateArithmetic(config.termCount);
  }

  // Build options
  const options = result.isShape
    ? buildShapeOptions(result.answer)
    : buildOptions(result.answer);

  return {
    sequence: result.sequence,
    answer: result.answer,
    options,
    rule: result.rule,
    hintText: result.hintText,
    patternType,
  };
};
